cat <<EOF | kubectl create -f - 
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
 containers:
 - name: nginx
   image: nginx
   ports:
    - containerPort:  8080
   resources:
     requests:
      memory: "60Mi"
      cpu: "1"
     limits:
       memory: "100Mi"
       cpu: "2"
EOF