cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
 name: app-secret
data:
  DB_Host: bX1zcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzd3Jk
EOF

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: nginx
    ports:
    - containerPort: 8080
    envFrom:
    - secretRef:
        name: app-secret
EOF

# kubectl describe secret app-secret
# kubectl get secret app-secret -o yaml
