
cat << EOF | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
EOF

kubectl get deployment
kubectl describe deployment dep-name
kubectl scale --replicas=6 deployment myapp-deployment

kubectl edit deployment myapp-deployment
press i to open in insert mode and then update replicas from 2 to 4
to save: press ESC
:wq! (enter)

kubectl delete deployment myapp-deployment

kubectl create deployment --image=httpd httpd-frontend --replicas=3
kubectl edit deployment httpd-frontend
press i to open in insert mode and then update replicas from 2 to 4
to save: press ESC
:wq! (enter)
