cat << EOF | kubectl create -f -
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-vol1
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 100Mi
  hostPath:
   path: /tmp/data
EOF

# Check persistent volume
kubectl get pv

spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 100Mi
  gcePersistentDisk:
   pdName: pd-disk
   fsType: ext4



spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 100Mi
  awsElasticBlockStore:
   volumeId: volumeId
   fsType: ext4

