cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    ports:
    - containerPort: 80

EOF


# sudo cat /etc/kubernetes/manifests/kube-apiserver.yaml