cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
  name: nginx
spec:
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerPort: 8080
 nodeName: node02
EOF

# Verify node for above pod 
kubectl get pods -o wide

# Try editing pod with different,say node01, should result in error
kubectl edit pod nginx 