cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john
spec:
  signerName: kubernetes.io/kube-apisever-client
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - client auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0djMkZvWkdWMk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXBUak4xVjlvLyt5NVpPcnJ0UWZZWlYyRCtkVFY3RXA4M2h6WUdRSlBlNzFKCmVvallPNUZKQndYOXhJUWVsYUpDdWRoVkoxT1U4bFk0dGJoejNmUExQajU2VjVvWGF5WGRVeVhQdXJHeEgrcGEKUUMzV3FlMXJtQjI3bmFkWlpjUU4yMzZhUWhScGJjSlMvUlB3UklOZWhVUmRDTk9WNW41QWtUNmNzQzFUVGRUQQo1ZS9yWllHc01kOGtKaGRYTnZaaDJReFkyK2JBdlNKcWRaQmlHakhobHIwSUVNS01rNzNQUzJ4NGJDVFczM1JxCkVPZUJOU1FZYWpLN1BORXhGdEkxYU1RTHI0TjJLbVFnYlNteGJRdCtXNTJwSjh1TVFtakxUTHhYeFNHb0dMQlQKT3p5cHlwSjdRaVpDWjNMelJwZVRNNU9CRzcxZHBIRkY5WEhHeFNKcHJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQTFWSUFJU080ZDJncWFMa2Foa1pqVnhaZmZHWHBwM0drcGdudXEybDdIRDBNb0RBSnJsCitWMHJOYU52VGlaVytRZVJXdjJncHVEblFjMzNvbXBFWEpTK0gvdktSSzdPS2IzNWdVV0ZwVjUyV0pTL2d1MGIKN2dEQk81bm02MEdDdjhwaFp1ZWtZYnRQanl6MjM3NnFKT1UzMlNmbTFhMUNOUUdIOEVvQXM1a1MrREtzckJoRwo1bGJvYU9HWnRud0hUQnhvMTdtMTFteXQ1N2s1eVpjOGFjaWluYzdzR0gxUU1IeEpvVVdwY2JCVXIyNjBiZEJRCk1pWXVQSjZtekJVczUzaEJUNTcxaXJRYzhLNmNONFRJVTVkL1ZTem5mbUhUNFhncnY4ZUJMNVczWnZaQlY2cmIKUkJzRFd6aTd5bk9ZcERtdkJ2SThITk12THpqQXlBUi9QMjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
EOF

sudo kubeadm certs check-expiration
openssl x509 -in /etc/kubernetes/pki/apiserver.crt -text -noout

  sudo openssl genrsa -out john.key 2048
  sudo openssl req -new -key john.key -subj "/CN=john" -out john.csr
  cat john.csr | base64 | tr -d "\n"
  kubectl get csr
  kubectl certificate approve john
  kubectl get csr john -o yaml
