kubectl config view

cat .kube/config

kubectl config current-context

kubectl config use-context prod-user@production (this will update current context in config file as well)

kubectl config set-context --current --namespace=dev (this will update the config file with new namespace)

curl https://localhost:6443/version -k
curl https://localhost:6443/api/v1/namespaces -k --cert admin.crt --key admin.key

